'use client'
import {useMemo,useState} from 'react'
import {Home,DoorOpen,Zap,Droplets,Receipt,Wallet,BarChart3,Settings,Plus,X} from 'lucide-react'

type Room={id:number;code:string;tenant:string;phone:string;rent:number;status:'Đang thuê'|'Trống';electricOld:number;waterOld:number}
type Invoice={id:number;room:string;month:string;rent:number;electric:number;water:number;other:number;total:number;paid:number;status:string}
const initialRooms:Room[]=[
{id:1,code:'A01',tenant:'Nguyễn Văn An',phone:'0901234567',rent:2500000,status:'Đang thuê',electricOld:1200,waterOld:80},
{id:2,code:'A02',tenant:'Trần Thị Lan',phone:'0912345678',rent:2500000,status:'Đang thuê',electricOld:980,waterOld:64},
{id:3,code:'A03',tenant:'',phone:'',rent:2500000,status:'Trống',electricOld:0,waterOld:0},
{id:4,code:'B01',tenant:'Lê Minh Đức',phone:'0987654321',rent:3000000,status:'Đang thuê',electricOld:1500,waterOld:100},
]
const initialInvoices:Invoice[]=[
{id:1,room:'A01',month:'10/2026',rent:2500000,electric:420000,water:160000,other:50000,total:3130000,paid:3130000,status:'Đã thu'},
{id:2,room:'A02',month:'10/2026',rent:2500000,electric:297500,water:120000,other:0,total:2917500,paid:1000000,status:'Còn nợ'},
{id:3,room:'B01',month:'10/2026',rent:3000000,electric:350000,water:180000,other:0,total:3530000,paid:0,status:'Chưa thu'},
]
const money=(n:number)=>n.toLocaleString('vi-VN')+' ₫'
export default function App(){
 const [tab,setTab]=useState('dashboard'); const [rooms,setRooms]=useState(initialRooms); const [invoices,setInvoices]=useState(initialInvoices); const [modal,setModal]=useState(false)
 const stats=useMemo(()=>{const due=invoices.reduce((s,x)=>s+x.total,0),paid=invoices.reduce((s,x)=>s+x.paid,0);return {due,paid,debt:due-paid,occupied:rooms.filter(r=>r.status==='Đang thuê').length}},[invoices,rooms])
 const nav=[['dashboard','🏠','Dashboard'],['rooms','🚪','Phòng & người thuê'],['meters','⚡','Điện nước'],['invoices','🧾','Hóa đơn'],['payments','💰','Thu tiền'],['reports','📊','Báo cáo'],['settings','⚙️','Cài đặt']]
 const addRoom=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setRooms([...rooms,{id:Date.now(),code:String(f.get('code')),tenant:String(f.get('tenant')),phone:String(f.get('phone')),rent:Number(f.get('rent')),status:'Đang thuê',electricOld:0,waterOld:0}]);setModal(false)}
 return <div className="app"><aside className="side"><div className="brand">🏠 Nhà Trọ Manager</div><div className="nav">{nav.map(([id,ic,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{ic}　{label}</button>)}</div></aside><main className="main">
 <div className="top"><div><div className="title">{nav.find(x=>x[0]===tab)?.[2]}</div><div className="sub">Tháng 10/2026 · Quản lý thu tiền nhà trọ</div></div>{(tab==='rooms'||tab==='meters')&&<button className="btn primary" onClick={()=>setModal(true)}><Plus size={16}/> Thêm phòng</button>}</div>
 {tab==='dashboard'&&<><div className="grid"><Stat l="Tổng số phòng" v={rooms.length.toString()} c="blue"/><Stat l="Đang cho thuê" v={stats.occupied.toString()} c="green"/><Stat l="Đã thu tháng này" v={money(stats.paid)} c="green"/><Stat l="Còn phải thu" v={money(stats.debt)} c="red"/></div><div className="section"><div className="sectionhead"><h2>Hóa đơn tháng 10/2026</h2><button className="btn light" onClick={()=>setTab('invoices')}>Xem tất cả</button></div><InvoiceTable invoices={invoices}/></div><div className="section"><div className="grid"><Stat l="Tiền phòng" v={money(invoices.reduce((s,x)=>s+x.rent,0))} c="blue"/><Stat l="Tiền điện" v={money(invoices.reduce((s,x)=>s+x.electric,0))} c="orange"/><Stat l="Tiền nước" v={money(invoices.reduce((s,x)=>s+x.water,0))} c="blue"/><Stat l="Tỷ lệ đã thu" v={stats.due?Math.round(stats.paid/stats.due*100)+'%':'0%'} c="green"/></div></div></>}
 {tab==='rooms'&&<><div className="section"><div className="sectionhead"><h2>Danh sách phòng</h2><span className="sub">{rooms.length} phòng · {stats.occupied} đang thuê</span></div><div className="tablewrap"><table className="table"><thead><tr><th>Phòng</th><th>Người thuê</th><th>SĐT</th><th>Giá phòng</th><th>Trạng thái</th></tr></thead><tbody>{rooms.map(r=><tr key={r.id}><td><b>{r.code}</b></td><td>{r.tenant||'—'}</td><td>{r.phone||'—'}</td><td>{money(r.rent)}</td><td><span className={'badge '+(r.status==='Đang thuê'?'paid':'due')}>{r.status}</span></td></tr>)}</tbody></table></div></div></>}
 {tab==='meters'&&<Meters rooms={rooms}/>} {tab==='invoices'&&<div className="section"><InvoiceTable invoices={invoices}/></div>}
 {tab==='payments'&&<div className="section"><div className="grid"><Stat l="Tổng phải thu" v={money(stats.due)} c="blue"/><Stat l="Đã thu" v={money(stats.paid)} c="green"/><Stat l="Còn nợ" v={money(stats.debt)} c="red"/><Stat l="Số hóa đơn" v={invoices.length.toString()} c="orange"/></div><div className="section"><InvoiceTable invoices={invoices}/></div></div>}
 {tab==='reports'&&<div className="section"><div className="card"><h2>Báo cáo tháng 10/2026</h2><p>Tổng tiền phòng: <b>{money(invoices.reduce((s,x)=>s+x.rent,0))}</b></p><p>Tổng tiền điện: <b>{money(invoices.reduce((s,x)=>s+x.electric,0))}</b></p><p>Tổng tiền nước: <b>{money(invoices.reduce((s,x)=>s+x.water,0))}</b></p><p>Tổng phải thu: <b>{money(stats.due)}</b></p><p>Đã thu: <b className="green">{money(stats.paid)}</b></p><p>Còn nợ: <b className="red">{money(stats.debt)}</b></p></div></div>}
 {tab==='settings'&&<div className="section"><div className="card"><h2>Đơn giá mặc định</h2><div className="formgrid"><Field label="Giá điện (đ/kWh)" value="3500"/><Field label="Giá nước (đ/m³)" value="20000"/><Field label="Ngày đến hạn" value="10"/></div></div></div>}
 {modal&&<div className="modalbg"><div className="modal"><div className="sectionhead"><h2>Thêm phòng</h2><button className="btn light" onClick={()=>setModal(false)}><X/></button></div><form onSubmit={addRoom}><div className="formgrid"><Field name="code" label="Mã phòng"/><Field name="tenant" label="Người thuê"/><Field name="phone" label="Số điện thoại"/><Field name="rent" label="Giá phòng" value="2500000"/><div className="full"><div className="actions"><button type="button" className="btn light" onClick={()=>setModal(false)}>Hủy</button><button className="btn primary">Lưu phòng</button></div></div></div></form></div></div>}
 </main></div>
}
function Stat({l,v,c}:{l:string;v:string;c:string}){return <div className="card"><div className="label">{l}</div><div className={'value '+c}>{v}</div></div>}
function Field({label,name,value}:{label:string;name?:string;value?:string}){return <div className="field"><label>{label}</label><input name={name} defaultValue={value}/></div>}
function InvoiceTable({invoices}:{invoices:Invoice[]}){return <div className="tablewrap"><table className="table"><thead><tr><th>Phòng</th><th>Tháng</th><th>Tiền phòng</th><th>Điện</th><th>Nước</th><th>Tổng</th><th>Đã thu</th><th>Trạng thái</th></tr></thead><tbody>{invoices.map(x=><tr key={x.id}><td><b>{x.room}</b></td><td>{x.month}</td><td>{money(x.rent)}</td><td>{money(x.electric)}</td><td>{money(x.water)}</td><td><b>{money(x.total)}</b></td><td>{money(x.paid)}</td><td><span className={'badge '+(x.status==='Đã thu'?'paid':'due')}>{x.status}</span></td></tr>)}</tbody></table></div>}
function Meters({rooms}:{rooms:Room[]}){return <div className="section"><div className="card"><h2>Nhập chỉ số điện nước tháng 10/2026</h2><div className="tablewrap"><table className="table"><thead><tr><th>Phòng</th><th>Điện cũ</th><th>Điện mới</th><th>Số điện</th><th>Nước cũ</th><th>Nước mới</th><th>Số nước</th></tr></thead><tbody>{rooms.filter(r=>r.status==='Đang thuê').map(r=><tr key={r.id}><td><b>{r.code}</b></td><td>{r.electricOld}</td><td><input style={{width:90,padding:7,border:'1px solid #ddd',borderRadius:7}} defaultValue={r.electricOld+100}/></td><td>100 kWh</td><td>{r.waterOld}</td><td><input style={{width:90,padding:7,border:'1px solid #ddd',borderRadius:7}} defaultValue={r.waterOld+7}/></td><td>7 m³</td></tr>)}</tbody></table></div><div className="actions"><button className="btn primary">Lưu chỉ số</button></div></div></div>}
